### ISSUE TITLE
内核抢占的矛盾点疑问

### ISSUE THREAD

**Issue by Loyolichoo** [freelancer-leon/notes#4]
arch/x86/entry/entry_64.S这个文件中retint_kernel里`jnc 1f`这段是判断cf标志位，在它的上一句`bt $9 EFLAGS(%rsp)`中，应该获取的是eflags的第九位if标志到cf中，如果中断是开启的，此时cf应该是1，为什么在这里反而是判断cf是0呢？

**Comment by freelancer-leon** [comment]
是的，此时 `CF=0` 表示中断关闭，不能进行内核抢占。
已修正，谢谢！
